### ISSUE TITLE
token？

### ISSUE THREAD

**Issue by hongmaoxiao** [lijiarui/developer-plan#3]
好奇是什么免费token

**Comment by lijiarui** [comment]
@hongmaoxiao 如果我项目贡献代码，或者写相关博客，会发送token，是微信接入的token，不是区块链的token :)

**Comment by hongmaoxiao** [comment]
> @hongmaoxiao 如果我项目贡献代码，或者写相关博客，会发送token，是微信接入的token，不是区块链的token :)

了解
